version: "3"

# Ref.
# - https://taskfile.dev/

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -l --sort none

  run:
    desc: "Run the application"
    cmds:
      -  uv run python main.py

  fmt:
    desc: "Format code using ruff"
    cmds:
      - uv run ruff format .

  lint:
    desc: "Lint code using ruff"
    cmds:
      - uv run ruff check .

  test:
    desc: "Run tests using pytest"
    cmds:
      - uv run pytest tests

  check-all:
    desc: "Check all code using ruff"
    cmds:
      - task fmt
      - task lint
      - task test
